productpagepr/Controllers/UserNotificationController.cs
using productpagepr.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace productpagepr.Controllers
{
    public class UserNotificationController : Controller
    {


        string constring = @"Data Source=DESKTOP-CIV7264\SQLEXPRESS;Initial Catalog=LifeServeBD_DB;Integrated Security=True";
        [HttpGet]

        public ActionResult notifUser()
        {
            dynamic ob = new ExpandoObject();
            ob.Usernotif = getUsernotif();

            return PartialView(ob);
        }
        public List<ReplyModel> getUsernotif()
        {
            List<ReplyModel> Usernotif = new List<ReplyModel>();
            string query = "select * from Reply ";
            //string constring = @"Data Source=DESKTOP-CIV7264\SQLEXPRESS;Initial Catalog=LifeServeBD_DB;Integrated Security=True";
            using (SqlConnection con = new SqlConnection(constring))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Usernotif.Add(new ReplyModel
                            {
                                UserId = sdr["UserId"].ToString(),
                                Id = (int)sdr["Id"],
                                Msg_Id = (int)sdr["Msg_Id"],
                                //datetim = Convert.ToDateTime(sdr["Datetm"]),
                            }) ;
                        }
                        con.Close();
                        return Usernotif;
                    }
                }
            }
        }
        // GET: UserNotification
        public ActionResult AllUsernotif()
        {
            //string constring = @"Data Source=DESKTOP-K860ERO;Initial Catalog=connection;Integrated Security=True";

            SqlConnection con = new SqlConnection(constring);
            string qt = "select Id,Msg_Id,Reply,UserId from Reply order by Id desc";
            con.Open();
            SqlCommand cmdt = new SqlCommand(qt, con);
            DataTable ddt = new DataTable();
            SqlDataAdapter adaptert = new SqlDataAdapter(cmdt);
            adaptert.Fill(ddt);

            return View(ddt);


        }
        public ActionResult Reply(int Id)
        {

            /*
            SqlConnection con = new SqlConnection(constring);
            String q = "select Id,Msg_Id ,Reply,Helpline.Message from Reply where Msg_Id like '" + Msg_Id + "'" + " INNER JOIN Helpline ON Reply.Msg_Id=Helpline.Id";

            con.Open();
            SqlCommand cmd = new SqlCommand(q, con);

            DataTable dt = new DataTable();
            SqlDataAdapter adapter = new SqlDataAdapter(cmd);

            adapter.Fill(dt);

            return View(dt);*/
            

                dynamic ob = new ExpandoObject();
                ob.msg= getMsg(Id);
            ob.Reply = getReply(Id);

            return View(ob);
            }

            public List<HelplineModel> getMsg(int Id)
            {
            List<HelplineModel> mesag = new List<HelplineModel>();
            string query = "select Id,Subject,Message,imgid,Prescription,UserId from Helpline where Id like '" + Id + "'" ;

            //string constring = @"Data Source=DESKTOP-CIV7264\SQLEXPRESS;Initial Catalog=LifeServeBD_DB;Integrated Security=True";
            using (SqlConnection con = new SqlConnection(constring))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            mesag.Add(new HelplineModel
                            {
                                Id = (int)(sdr["Id"]),
                                UserId = sdr["UserId"].ToString(),

                                Subject = sdr["Subject"].ToString(),
                                Message = sdr["Message"].ToString(),
                                imgid = sdr["imgid"].ToString(),
                                Prescription = sdr["Prescription"].ToString(),

                            });
                        }
                    }
                    con.Close();
                    return mesag;

                }

                
            }
            }


        public List<ReplyModel> getReply(int Id)
        {
            List<ReplyModel> rep = new List<ReplyModel>();
            string query = "select Id,Msg_Id,Reply,UserId from Reply where Id like '" + Id + "' ";

            //string constring = @"Data Source=DESKTOP-CIV7264\SQLEXPRESS;Initial Catalog=LifeServeBD_DB;Integrated Security=True";
            using (SqlConnection con = new SqlConnection(constring))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            rep.Add(new ReplyModel
                            {
                                //Id = (int)(sdr["Id"]),
                               // Msg_Id =(int)(sdr["Msg_Id"]),
                               //Subject = sdr["Subject"].ToString(),
                                //Message = sdr["Message"].ToString(),
                                //imgid = sdr["imgid"].ToString(),
                                Reply = sdr["Reply"].ToString(),
                                UserId=sdr["UserId"].ToString()
                            });
                        }
                    }
                    con.Close();
                    return rep;

                }


            }
        }

        }

    }

productpagepr/Views/UserNotification/AllUsernotif.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "AllUserotification";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <link href="~/style/commonElements.css" rel="stylesheet" />
<body>

    <div class="card" style="margin: auto; background-origin:border-box;backface-visibility:hidden;
        margin-top: 5%;
        height: 700px;
        overflow: scroll;
        overflow-x: hidden;
        width: 80%;">
        <div class="card-body alert alert-success">


            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                if (String.Equals(Session["userId"], @Model.Rows[i][3]))
                {
                <div class="notifi__item my-3" style="display:flex;justify-content:space-between;">

                    <div class="content">
                        <p style="font-size:20px ">Your Message has been replied </p>
                    </div>


                    <div>
                        @using (Html.BeginForm("Reply", "UserNotification", FormMethod.Get))
                        {
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="Id" value="@Model.Rows[i][0]" />
                            <button class="my-3 btn btn-success" type="submit" style="font-size:22px">View Reply</button>

                        }
                    </div>
                </div>
                <hr />
                }
            }
        </div>

    </div>

</body>

productpagepr/Views/UserNotification/Reply.cshtml
@using productpagepr.Models;

@model dynamic
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Index";

}


<link href="~/style/commonElements.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
      integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

<!-- jQuery Modal -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>



@*@using (Html.BeginForm("Reply", "UserNotification", FormMethod.Get))
    {*@

<center>

    <div class="message-box" style="background-color:#fbeded">
        <div class="headline1">

        </div>
        <div class="headline">

            <center>
                <br/>
                <h2 style="font-size:35px; font-weight:bolder;font-family:Apple Chancery, cursive;">Reply Of Your Message</h2>
            
 <br/>           </center>
            <div class="box-main" style="background-image: radial-gradient( circle 993px at 0.5% 50.5%,  rgba(137,171,245,0.37) 0%, rgba(245,247,252,1) 100.2% );width:60%">
                @foreach (HelplineModel msg in Model.msg)
                {
                    if (String.Equals(Session["userId"], msg.UserId))
                    {


                   
                        <h3 style="font-size:28px; font-weight:bolder;font-family:Bookman Old Style; color:#002347; margin-left:20px;"> Subject:</h3>
                    
                        <p style="border:1px solid #9affc8;color:#48bbc7; font-size:24px; font-weight:bold;font-family:Palatino Linotype; color:black; margin-left:20px;">
                        @msg.Subject
                    </p>
                   
                    <h3 style="font-size: 24px;font-weight: bolder;font-family: Bookman Old Style;color: #002347; margin-left: 20px">Message:</h3>
                    
                    <p style="border:1px solid #4c0611 ;color:#48bbc7;font-size:22px; font-weight:bold;font-family:Palatino Linotype; color:black; margin-left:20px;">
                        @msg.Message
                    </p>

                    <h3 style=" font-size: 24px;font-weight: bolder;font-family: Bookman Old Style; color: #002347;margin-left: 20px">Prescription:</h3>

                        if (msg.Prescription.ToString() != "No Prescription")
                        {
                        <img src=" @msg.imgid" style="max-height :500px;max-width :500px;border:1px solid #ffca05" />

                        }
                        else
                        {
                      
                            <p style="border:1px solid #e30048 ;color:#48bbc7;font-size:22px; font-weight:bold;font-family:Palatino Linotype; color:black; margin-left:20px;">@msg.Prescription</p>

                        }
                    }

                }

                @foreach (ReplyModel rpl in Model.Reply)
                {
                    if (String.Equals(Session["userId"], rpl.UserId))
                    {


                    <h3 style=" font-size: 24px;font-weight: bolder; font-family: Bookman Old Style; color: #002347; margin-left: 20px;">Reply:</h3>
                   
                    <p style="border:1px solid #d35400;color:#48bbc7;font-size:22px; font-weight:bold;font-family:Palatino Linotype; color:black; margin-left:20px;">
                        @rpl.Reply
                    </p>

                    <hr />
                    }
                }
                @* @using (Html.BeginForm("", "", FormMethod.Get))*@
                
                @Html.AntiForgeryToken()
                <p>
                    @*      input type="hidden" name="Id" value="@rpl.Id" />*@

                    <a style="border:1.5px solid #87d37c ;color: black;margin-left: 20%;margin-bottom: 10%;font-size: 24px; font-weight:bold; font-family: Bookman Old Style;" href="@Url.Action("index", "Helpline")" class="btn btn-default">Send a new Message</a>

                    <a style="border :1.5px solid  darkgreen;  color: black; font-size: 24px;font-weight:bold; font-family: Bookman Old Style; margin-right:20%;margin-bottom: 10%" href="@Url.Action("Index", "Home")" class="btn btn-default">Close</a>

                </p>

            </div>

        </div>

</center>

productpagepr/Views/UserNotification/notifUser.cshtml
@using productpagepr.Models;

@model dynamic

@{
    ViewBag.Title = "Usernotification";
}






@foreach (ReplyModel notif in Model.Usernotif)
{

    if (String.Equals(Session["userId"], notif.UserId))
    {

        <div class="content" style="border:1.5px solid #68c3a3;margin-bottom:1px;font-size:20px">
            <p>Your Message Has Been Replied &#128515;</p>
            @* <span class="date">
                @ViewData["fDt"]
                    </spa*@

            <div>
                @using (Html.BeginForm("Reply", "UserNotification", FormMethod.Get))
                {
                    @Html.AntiForgeryToken()
                    <input type="hidden" name="Id" value="@notif.Id" />
                    <button style="transform:translateY(50%);transform:translateX(230px);margin-bottom:2px;font-size:20px" type="submit" class="btn btn-default ">View Reply</button>

                }
                
            </div>
            
        </div>
    }
}