productpagepr/Controllers/AdminOrderController.cs
using productpagepr.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace productpagepr.Controllers
{
    public class AdminOrderController : Controller
    {
        // GET: AdminOrder

        string constring = @"Data Source=DESKTOP-CIV7264\SQLEXPRESS;Initial Catalog=LifeServeBD_DB;Integrated Security=True";


        // show order table in admin panel
        public ActionResult AdminOrderInfo(string searchString)
        {
            SqlConnection con = new SqlConnection(constring);
            String q = "select CustomerId,OrderId,ProductName,Category,Price,Quantity,TotalPrice,convert(varchar, Date_Time, 9),DATENAME(dw, Date_Time) as Day,id from OrderItem  " +
                " where OrderId Like '%" + searchString + "%' " +
                "or CustomerId Like '%" + searchString + "%' " +
                "or ProductName Like '%" + searchString + "%' " +
                "order by Date_Time desc";

            con.Open();
            SqlCommand cmd = new SqlCommand(q, con);

            DataTable dt = new DataTable();
            SqlDataAdapter adapter = new SqlDataAdapter(cmd);

            adapter.Fill(dt);

            return View(dt);

        }

        //delete a record

        public ActionResult Delete(int id)
        {
            SqlConnection con = new SqlConnection(constring);
            String q = "Delete from OrderItem where id=@id";
            con.Open();
            SqlCommand cmd = new SqlCommand(q, con);
            cmd.Parameters.AddWithValue("@id", id);

            cmd.ExecuteNonQuery();

            return RedirectToAction("AdminOrderInfo");
        }
    }
}

productpagepr/Views/AdminOrder/AdminOrderInfo.cshtml
@model System.Data.DataTable

@{

    Layout = "~/Views/Shared/AdminDashboardLayout.cshtml";
    ViewBag.Title = "AdminOrderInfo";
}
    <div style="margin-left:2%;">
        
        <br />
        <center>  <h2>Order List</h2> </center>
        <hr />
        <br />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" type="text/css" />

        <link href="vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all" />
        <div class="my-3" style="display:flex;justify-content:space-around;">
            <div>
                <form class="form-inline" action="AdminOrderInfo" method="get">
                    <input class="form-control" style="width:300px;border:none;" type="text" name="searchString" placeholder="Search order" />
                    <button class="btn btn-primary" type="submit">
                        <i class="zmdi zmdi-search"></i>
                    </button>
                </form>
            </div>
            
        </div>

        <div class="table-responsive ">
            <table class=" table table-hover table-fixed table-striped border-dark w-auto table1" style="background-color: white;">
                <thead class="thead-dark">
                    <tr>

                        <th> ID </th>
                        <th> Customer ID  </th>
                        <th> Order ID  </th>
                        <th> Product Name  </th>

                        <th> Category  </th>

                        <th> Price </th>
                        <th> Quantity </th>
                        <th> Total Price </th>

                        <th> Date &amp; Time  </th>
                        <th> Day  </th>
                        <th> Delete  </th>





                    </tr>
                </thead>

                @for (int i = 0; i < Model.Rows.Count; i++)
                {
                    <tbody>
                        <tr>
                            <td>@Model.Rows[i][9]</td>
                            <td>@Model.Rows[i][0]</td>
                            <td>@Model.Rows[i][1]</td>
                            <td>@Model.Rows[i][2]</td>
                            <td>@Model.Rows[i][3]</td>
                            <td>@Model.Rows[i][4]</td>
                            <td>@Model.Rows[i][5]</td>
                            <td>@Model.Rows[i][6]</td>
                            <td>@Model.Rows[i][7]</td>
                            <td>@Model.Rows[i][8]</td>

                            <td><a href="@Url.Action("Delete", "AdminOrder", new { @id = Model.Rows[i][9] })"><p style="color:red;">Delete</p></a></td>






                        </tr>
                    </tbody>
                }



            </table>
        </div>

        <script src="~/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>





    </div>


<style>

    .table-responsive {
        width: 1030px;
        height: 550px;
        font-size: 12px;
    }

    thead tr:first-child th {
        position: sticky;
        top: 0;
    }
    tr:nth-child(even) {
        background-color: white;
    }
</style>